#!/usr/bin/env bash

set -eEu -o pipefail

status() {
    echo "### $1"
}

status "Clean"
rm -rf dist/

status "Compile"
tsc

status "Bundle module"
rollup dist/fudgel.js --file dist/fudgel.mjs --format esm

status "Update docs"
cp dist/fudgel.mjs docs/fudgel.min.js
