#!/usr/bin/env bash

set -eEu -o pipefail

status() {
    echo "### $1"
}

status "Building"
npm run build

status "Tree shaking"
agadoo dist/fudgel.mjs

status "Cypress"
cypress run --component
start-server-and-test start http://localhost:8080 'cypress run --e2e'
