#!/usr/bin/env bash

set -eEu -o pipefail

status() {
    echo "### $1"
}

status "Building"
npm run build

status "Tree shaking"
agadoo dist/fudgel.mjs

status "Cypress (Electron)"
cypress run --component

status "Cypress (Chrome)"
cypress run --component --browser chrome
